from __future__ import annotations

import argparse
import getpass
import json
import logging
import pwd
import secrets
import shutil
import subprocess
from pathlib import Path

from .config import (
    BackupConfig,
    EdgeConfig,
    RecoveryConfig,
    RtspConfig,
    VideoConfig,
    render_toml,
    write_atomic,
)
from .doctor import run_checks
from .recovery import create_app
from .runner import EdgeRunner

DEFAULT_CONFIG = Path("/etc/ai-cctv-edge/config.toml")


def _prompt(label: str, default: str) -> str:
    value = input(f"{label} [{default}]: ").strip()
    return value or default


def setup(path: Path) -> int:
    device_id = _prompt("Device ID", "edge-001")
    camera_id = _prompt("Camera ID", "cam-001")
    mode = _prompt("RTSP mode (central_pull/central_publish)", "central_publish")
    central_host = _prompt("Central server address", "192.0.2.10")
    width = int(_prompt("Width", "1920"))
    height = int(_prompt("Height", "1080"))
    fps = int(_prompt("FPS", "30"))
    bitrate = int(_prompt("Bitrate (kbps)", "4000"))
    backup_root = Path(_prompt("Backup root", "/var/lib/ai-cctv-edge/recordings"))
    password_file = path.parent / "publish.password"
    recovery_token_file = path.parent / "recovery.token"
    config = EdgeConfig(
        schema_version=1,
        device_id=device_id,
        camera_id=camera_id,
        video=VideoConfig(width, height, fps, bitrate),
        rtsp=RtspConfig(
            mode=mode,
            central_host=central_host,
            username=camera_id,
            password_file=password_file,
        ),
        backup=BackupConfig(root=backup_root),
        recovery=RecoveryConfig(token_file=recovery_token_file),
    )
    config.validate()
    write_atomic(path, render_toml(config))
    if mode == "central_publish":
        publish_password = getpass.getpass(
            "Camera publish password generated by the server Configurator: "
        ).strip()
        if len(publish_password) < 16:
            raise ValueError("publish password must contain at least 16 characters")
        write_atomic(password_file, publish_password + "\n", mode=0o600)
    elif not password_file.exists():
        write_atomic(password_file, secrets.token_urlsafe(32) + "\n", mode=0o600)
    if not recovery_token_file.exists():
        write_atomic(recovery_token_file, secrets.token_urlsafe(48) + "\n", mode=0o600)
    try:
        account = pwd.getpwnam("ai-cctv-edge")
    except KeyError:
        account = None
    if account is not None:
        for target in (path, password_file, recovery_token_file):
            shutil.chown(target, user=account.pw_uid, group=account.pw_gid)
    print(f"Configuration written: {path}")
    print(f"Camera stream path: {camera_id}")
    print(
        f"Recovery token file (copy securely to the central operator): {recovery_token_file}"
    )
    return 0


def systemctl(action: str) -> int:
    return subprocess.run(
        ["systemctl", action, "ai-cctv-edge.service"], check=False
    ).returncode


def show_status(path: Path) -> int:
    subprocess.run(
        ["systemctl", "--no-pager", "--full", "status", "ai-cctv-edge.service"],
        check=False,
    )
    state = Path("/var/lib/ai-cctv-edge/state/status.json")
    if state.exists():
        print(state.read_text(encoding="utf-8"))
    else:
        print(json.dumps({"state": "unknown", "config": str(path)}))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ai-cctv-edge")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    sub = parser.add_subparsers(dest="command", required=True)
    for command in (
        "setup",
        "configure",
        "start",
        "stop",
        "restart",
        "status",
        "doctor",
        "logs",
        "run",
        "serve-recovery",
    ):
        sub.add_parser(command)
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s service=edge %(message)s",
    )
    if args.command in {"setup", "configure"}:
        result = setup(args.config)
        if result == 0 and args.config == DEFAULT_CONFIG:
            systemctl("enable")
            return systemctl("restart")
        return result
    if args.command in {"start", "stop", "restart"}:
        return systemctl(args.command)
    if args.command == "logs":
        return subprocess.run(
            ["journalctl", "-u", "ai-cctv-edge.service", "-f"], check=False
        ).returncode
    if args.command == "status":
        return show_status(args.config)
    if args.command == "doctor":
        config = EdgeConfig.load(args.config)
        checks = run_checks(config)
        for check in checks:
            print(f"[{check.status}] {check.name}: {check.message}")
        return 1 if any(check.status == "ERROR" for check in checks) else 0
    if args.command == "run":
        return EdgeRunner(args.config).run()
    if args.command == "serve-recovery":
        import uvicorn

        config = EdgeConfig.load(args.config)
        uvicorn.run(
            create_app(args.config),
            host=config.recovery.bind_host,
            port=config.recovery.port,
            log_config=None,
        )
        return 0
    parser.error("unsupported command")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
