"""Generate local central-server secrets without writing them to stdout."""

from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from configurator.private_files import restrict_private_file  # noqa: E402


CAMERA_ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")


def parse_args() -> argparse.Namespace:
    server_dir = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        help=(
            "write one legacy direct-development env file; Compose deployments "
            "must use split service files"
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=server_dir / "secrets",
        help="directory for data.env, external.env, inference.env, and media.env",
    )
    parser.add_argument(
        "--camera-id",
        action="append",
        default=[],
        help=(
            "bootstrap-only Camera publish credential to generate; may be repeated "
            "and does not rotate a DB-backed credential"
        ),
    )
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def single_quote(value: str) -> str:
    if "'" in value or "\n" in value or "\r" in value:
        raise ValueError("dotenv value contains an unsupported character")
    return f"'{value}'"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent, text=True
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        restrict_private_file(temporary_path)
        os.replace(temporary_path, path)
    finally:
        temporary_path.unlink(missing_ok=True)


def main() -> int:
    args = parse_args()

    camera_ids = list(dict.fromkeys(args.camera_id))
    for camera_id in camera_ids:
        if CAMERA_ID_PATTERN.fullmatch(camera_id) is None:
            raise SystemExit(f"invalid camera ID: {camera_id}")

    publish_credentials = {
        camera_id: {
            "username": camera_id,
            "password": secrets.token_urlsafe(32),
        }
        for camera_id in camera_ids
    }

    data_external_token = secrets.token_urlsafe(48)
    data_inference_token = secrets.token_urlsafe(48)
    data_media_token = secrets.token_urlsafe(48)
    data_recovery_token = secrets.token_urlsafe(48)
    jwt_secret = secrets.token_urlsafe(48)
    media_read_username = "inference-reader"
    media_read_password = secrets.token_urlsafe(48)
    media_credentials = single_quote(
        json.dumps(publish_credentials, separators=(",", ":"), sort_keys=True)
    )
    legacy_internal_token = secrets.token_urlsafe(48)
    combined_lines = [
        "# Legacy direct-development fallback; do not use with Docker Compose.",
        "# Generated by server/scripts/generate_secrets.py; do not commit.",
        f"INTERNAL_SERVICE_TOKEN={legacy_internal_token}",
        f"JWT_SECRET={jwt_secret}",
        f"DATA_INTERNAL_TOKEN={legacy_internal_token}",
        f"MEDIA_READ_USERNAME={media_read_username}",
        f"MEDIA_READ_PASSWORD={media_read_password}",
        "# Bootstrap-only; use the authenticated server rotation API after setup.",
        f"MEDIA_PUBLISH_CREDENTIALS_JSON={media_credentials}",
        "",
    ]
    if args.output is not None:
        outputs = {args.output.expanduser().resolve(): combined_lines}
    else:
        output_dir = args.output_dir.expanduser().resolve()
        outputs = {
            output_dir / "data.env": [
                "# Data Service only; do not commit.",
                f"DATA_EXTERNAL_TOKEN={data_external_token}",
                f"DATA_INFERENCE_TOKEN={data_inference_token}",
                f"DATA_MEDIA_TOKEN={data_media_token}",
                f"DATA_RECOVERY_TOKEN={data_recovery_token}",
                "",
            ],
            output_dir / "external.env": [
                "# External Service only; do not commit.",
                f"DATA_EXTERNAL_TOKEN={data_external_token}",
                f"JWT_SECRET={jwt_secret}",
                f"MEDIA_READ_USERNAME={media_read_username}",
                f"MEDIA_READ_PASSWORD={media_read_password}",
                "# Bootstrap-only; use the authenticated server rotation API after setup.",
                f"MEDIA_PUBLISH_CREDENTIALS_JSON={media_credentials}",
                "",
            ],
            output_dir / "inference.env": [
                "# Inference Service only; do not commit.",
                f"DATA_INFERENCE_TOKEN={data_inference_token}",
                f"MEDIA_READ_USERNAME={media_read_username}",
                f"MEDIA_READ_PASSWORD={media_read_password}",
                "",
            ],
            output_dir / "media.env": [
                "# MediaMTX recording hook only; do not commit.",
                f"DATA_MEDIA_TOKEN={data_media_token}",
                "",
            ],
        }
    existing = [path for path in outputs if path.exists()]
    if existing and not args.force:
        paths = ", ".join(str(path) for path in existing)
        raise SystemExit(f"refusing to overwrite existing file(s): {paths}")
    for output, lines in outputs.items():
        atomic_write(output, "\n".join(lines))

    print("[OK] generated " + ", ".join(str(path) for path in outputs))
    if camera_ids:
        print(
            "[INFO] generated bootstrap-only publish credentials for: "
            + ", ".join(camera_ids)
            + "; this does not rotate DB-backed credentials"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
