"""Generate local central-server secrets without writing them to stdout."""

from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import tempfile
from pathlib import Path


CAMERA_ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")


def parse_args() -> argparse.Namespace:
    server_dir = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=server_dir / "secrets" / "secrets.env",
    )
    parser.add_argument(
        "--camera-id",
        action="append",
        default=[],
        help="Camera publish credential to generate; may be repeated",
    )
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def single_quote(value: str) -> str:
    if "'" in value or "\n" in value or "\r" in value:
        raise ValueError("dotenv value contains an unsupported character")
    return f"'{value}'"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent, text=True
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary_path, 0o600)
        os.replace(temporary_path, path)
    finally:
        temporary_path.unlink(missing_ok=True)


def main() -> int:
    args = parse_args()
    output = args.output.expanduser().resolve()
    if output.exists() and not args.force:
        raise SystemExit(f"refusing to overwrite existing file: {output}")

    camera_ids = list(dict.fromkeys(args.camera_id))
    for camera_id in camera_ids:
        if CAMERA_ID_PATTERN.fullmatch(camera_id) is None:
            raise SystemExit(f"invalid camera ID: {camera_id}")

    publish_credentials = {
        camera_id: {
            "username": f"edge-{camera_id}",
            "password": secrets.token_urlsafe(32),
        }
        for camera_id in camera_ids
    }

    internal_service_token = secrets.token_urlsafe(48)
    lines = [
        "# Generated by server/scripts/generate_secrets.py; do not commit.",
        f"JWT_SECRET={secrets.token_urlsafe(48)}",
        f"INTERNAL_SERVICE_TOKEN={internal_service_token}",
        f"DATA_INTERNAL_TOKEN={internal_service_token}",
        "MEDIA_PUBLISH_CREDENTIALS_JSON="
        + single_quote(
            json.dumps(publish_credentials, separators=(",", ":"), sort_keys=True)
        ),
        "",
    ]
    atomic_write(output, "\n".join(lines))

    print(f"[OK] generated {output}")
    if camera_ids:
        print("[INFO] generated publish credentials for: " + ", ".join(camera_ids))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
